name: "Validation And Formatting"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.6.0
        name: Setup Python
      - uses: actions/cache@v4
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: astral-sh/ruff-action@v3
        with:
          # TODO: Remove these ignores, but right now there's too many issues
          args: "check --ignore F405,F403,E722"
      - uses: hacs/action@22.5.0
        with:
          CATEGORY: integration
